# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

target 'SwiftNews' do
  use_frameworks!

  # Pods for SwiftNews
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SnapKit'
  pod 'UIColor_Hex_Swift'
end

target 'SwiftNewsSpec' do
  use_frameworks!
  testing_pods
  pod 'SnapKit'
  pod 'UIColor_Hex_Swift'
end
